# Generated by Django 4.1.3 on 2025-12-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_alter_booking_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room_type',
            new_name='RoomType',
        ),
    ]
