# Generated by Django 4.1.3 on 2025-12-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0015_rename_room_type_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
